### ISSUE TITLE
Cannot be installed with composer

### ISSUE THREAD

**Issue by masi** [b13/trusted-url-params#3]
There is no tag matching the 1.0.0 release.

**Comment by bmack** [comment]
Yes. Because it is currently being tested internally, and therefor no tag / release has been created nor uploaded to TER.

**Comment by masi** [comment]
It is already advertised as a replacement for the abandoned sourcebroker/urlguard.

**Comment by bmack** [comment]
What's wrong with using the package with dev-main?

**Comment by masi** [comment]
Well, it was you who wrote that is an **internal** beta for now.

**Comment by bmack** [comment]
it's not an internal beta (it's a public beta) but we're using it in our companies projects to see if we have side-effects. I'm happy if you also could test. Otherwise, I can also provide a 0.1.0 version right away, would that be sufficient for you?

**Comment by masi** [comment]
The version number does not matter that much. It is the trust the authors shows to his own code ;)

**Comment by bmack** [comment]
We've just published v1.0.0. Enjoy!
